### ISSUE TITLE
Convertible in java?

### ISSUE THREAD

**Issue by GauravCreed** [AntonPopoff/android-color-wheel#40]
Hi @thegrandpoobah 

how can I write listener of **ColorWheel** and **GradientSeekBar** in java file ?

Thanks (_).

**Comment by thegrandpoobah** [comment]
hi @GauravCreed , I'm not sure if you intended to msg me on this one. I'm actually not the maintainer for this project or very good with Kotlin to begin with, but here is some documentation from the Kotlin documentation on how to use Kotlin code in Java that might serve as a good starting point: https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html

**Comment by AntonPopoff** [comment]
Hi @GauravCreed.

If your project is written in pure Java without Kotlin's standard library dependency unfortunately it's impossible to set a listener from Java code. In Java Kotlin's functional types are converted to `Function1`, `Function2`, … interfaces which come with Kotlin's standard library.

**Comment by AntonPopoff** [comment]
Even though Kotlin 1.4 has functional interfaces which make it possible to write an interface for a listener, which Java code will recognize as a usual interface and Kotlin will still allow usage of Kotlin style lambdas, there are still several cases when Kotlin will require explicit type casts which will break the existing code until it is refactored.
